import React from 'react'
import Head from 'next/head'
function chat() {
  return (
    <div>
    <Head>
    <title>chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
        <h1>This is a chat page</h1>
    </div>
  )
}

export default chat